{{ 
    config (
        materialized = "table",
        pre_hook = "{{ copy_csvs('FACT_CP') }}",
        schema = 'RAW_DATA'

    )
}}

WITH fact_raw AS 
(
    SELECT 
    *,
    CURRENT_TIMESTAMP(6) AS CREATED_AT
    FROM {{source('fact','FACT_CP')}}
)
SELECT
STORE,
DATE,
CAST(TEMPERATURE AS FLOAT) AS TEMPERATURE,
CAST(FUEL_PRICE AS FLOAT) AS FUEL_PRICE,
CAST(MARKDOWN1 AS FLOAT) AS MARKDOWN1,
CAST(MARKDOWN2 AS FLOAT) AS MARKDOWN2,
CAST(MARKDOWN3 AS FLOAT) AS MARKDOWN3,
CAST(MARKDOWN4 AS FLOAT) AS MARKDOWN4,
CAST(MARKDOWN5 AS FLOAT) AS MARKDOWN5,
CAST(CPI AS FLOAT) AS CPI,
CAST(UNEMPLOYMENT AS FLOAT) AS UNEMPLOYMENT,
CAST(ISHOLIDAY AS BOOLEAN) AS ISHOLIDAY,
CAST(CREATED_AT AS TIMESTAMP(6)) AS CREATED_AT
FROM fact_raw