-- Initial Setup scripts for creating the Database,Schema and Copy tables.

USE ROLE ACCOUNTADMIN;

USE warehouse COMPUTE_WH;

-- Create Database

CREATE OR REPLACE DATABASE WALMARTDB;


-- Create Schema

CREATE OR REPLACE SCHEMA WALMARTDB.DATA;

USE SCHEMA WALMARTDB.DATA;

-- Create Storage_integration

CREATE OR REPLACE STORAGE INTEGRATION WALMARTDB_S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED= TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::229378727976:role/walmart_snowflake_role'
STORAGE_ALLOWED_LOCATIONS = ('s3://walmart-s3-raw-data-bucket/raw_data/');

DESC INTEGRATION WALMARTDB_S3_INT;

-- Create Department Copy Table

CREATE OR REPLACE TABLE DEPARTMENT_CP
(
STORE INT,
DEPT INT,
DATE DATE,
WEEKLY_SALES DECIMAL,
ISHOLIDAY VARCHAR
);

-- Create Fact Copy Table

CREATE OR REPLACE TABLE FACT_CP
(
STORE INT,
DATE DATE,
TEMPERATURE DECIMAL,
FUEL_PRICE DECIMAL,
MARKDOWN1 DECIMAL,
MARKDOWN2 DECIMAL,
MARKDOWN3 DECIMAL,
MARKDOWN4 DECIMAL,
MARKDOWN5 DECIMAL,
CPI DECIMAL,
UNEMPLOYMENT DECIMAL,
ISHOLIDAY VARCHAR
);

-- Create Stores Copy Table

CREATE OR REPLACE TABLE STORES_CP
(
STORE INT,
TYPE VARCHAR,
SIZE INT
);

-- Create External Stage 

CREATE OR REPLACE STAGE WALMARTDB.DATA.WALMARTDB_S3_STAGE
STORAGE_INTEGRATION = WALMARTDB_S3_INT
URL = 's3://walmart-s3-raw-data-bucket/raw_data/';

-- List the stages 

ls @WALMARTDB.DATA.WALMARTDB_S3_STAGE;

-- create file format

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n'
SKIP_HEADER = 1
NULL_IF = ('NA');









